### ISSUE TITLE
> Use GCC 4.8 (not 4.9 or newer, as those versions have more aggressive optimisation which cause hardware registers to be read incorrectly and consequently the bootloader does not work)

### ISSUE THREAD

**Issue by l29ah** [rogerclarkmelbourne/STM32duino-bootloader#101]
Does this bug still exist, 7 years after the gcc release, noting that such old versions aren't supported by any modern Linux distro?

**Comment by l29ah** [comment]
Huh?

**Comment by rogerclarkmelbourne** [comment]
This issue is over a year old

No one replied.

I dont know the answer.

You would need to test this youself
