### ISSUE TITLE
STM32f103c8t6 blue pill char length larger then 255 won't work

### ISSUE THREAD

**Issue by Danilo277** [rogerclarkmelbourne/STM32duino-bootloader#106]
Hello everyone, please help. The problem is this: a char array cannot be larger than 255, why? Here is an example:
....
if (Serial.available() > 0) {
char incoming[400];
Serial.readBytes(incoming,400);
Serial.println(incoming);
}
....
So, when I send ower serial text that is, for example, 350 characters long, serial read only 255.
if I make:
....
if (Serial.available() > 0) {
char incoming[400];
String string=Serial.readString();
Serial.println(string);

string.toCharArray(incoming,400);
Serial.println(incoming);
}
....

now String works perfect but char is limited to 255.
Thanks in advance.

**Comment by rogerclarkmelbourne** [comment]
You have posted to the wrong place.

This is the repo for a bootloader.

I suggest you post to a STM32 Arduino user group like

https://www.stm32duino.com/
