### ISSUE TITLE
The GD bootloader doesn't work with GD32 E103

### ISSUE THREAD

**Issue by umartechboy** [rogerclarkmelbourne/STM32duino-bootloader#107]
I'm not talking about F103. Its E103 with the cortex M4 core.  

I've uploaded the bootloader using STlink V2 on a bluepill board with this IC. It does upload but does not work. I'm using gd32f1_generic_boot20_pc13.bin. It gives that LED blinking but the USB Device descriptor fails. To confirm its a bootloader issue, I swapped the IC with STM32F103C8 and even a CKS32F103C8 and the Naze32 bootloader does the trick. DFU and maple serial start to work. So the USB hardware on the bluepill board must be OK and the resistor values on D+ and D- must be good enough. To confirm that my GD IC was not faulty, I swapped it back, and another trick worked by chance

https://github.com/vllogic/vllink_lite/releases/tag/v0.8.3

This repo contains a bootloader+firmware for some V-Link device. Its some debugging device. I flashed the booloader bin and a "VLink" device appears in my USB devices under Unversal Serial Bus devices. So the HW must be OK on my board and the IC right? 

It must be happening because I'm using E103 instead of F103. I have always wriiten user applications for STM. Did bootloaders only on AVR. So I don't have any idea were tos tart. Can someone at least point me in the direction to rebuild the booatloader on my own? only then will I be able to compare what VLink is doing and what we guys are doing in this bootloader, and find what worked for them and not for us.

**Comment by rogerclarkmelbourne** [comment]
This bootloader is written to run on the STM32F103, not other devices, even if they seem similar on paper.
