### ISSUE TITLE
STM32F103C8 doesn't restart when the serial monitor is opened

### ISSUE THREAD

**Issue by redbeard122** [rogerclarkmelbourne/STM32duino-bootloader#111]
the STM32F103CB  doesn't reset when the serial monitor is opened unlike all other arduino boards
does this mean the RTS (request to send) doesn't work or there is an issue ? 
also i'd like to know if this is a hardware or software issue
I am using generic_boot20_pc13.bin as a bootloader
Thanks in advanced

**Comment by rogerclarkmelbourne** [comment]
"Arduino" boards are completely different, they use a hardware reset from the sepearte USB to serial chip
