### ISSUE TITLE
Support DR4 as magic boot value register

### ISSUE THREAD

**Issue by StefanBruens** [rogerclarkmelbourne/STM32duino-bootloader#113]
Newer Arduino versions use DR4 instead of DR10 for the magic value, see
https://github.com/Serasidis/STM32_HID_Bootloader/issues/13

**Comment by rogerclarkmelbourne** [comment]
I am no longer actively supporting this bootloader

Also, I see from your link ,

https://github.com/Serasidis/STM32_HID_Bootloader/issues/13

 that the issue you referenced was closed by the author of that bootloader

 @Serasidis Serasidis closed this on 12 Jun 2019

**Comment by StefanBruens** [comment]
The referenced issue was closed, at it was fixed.

Also, if you close this, you should close all other issues, and put a note on the front page ...
