### ISSUE TITLE
tmk_core/common/chibios/pin_defs.h:226:25: error: 'GPIOF' undeclared here (not in a function); did you mean 'GPIOB'?

### ISSUE THREAD

**Issue by mianqi2016** [rogerclarkmelbourne/STM32duino-bootloader#115]
I tried this bootloader on a stm32f103c6t6 minimal circuit, it has only a "RESET" button on and two jumpers for BOOT0 and BOOT1. I want to use "qmk flash" on it. The keyboard I selected was "crkbd" and I have modified in the "rules.mk" file under directory "crkbd":

> # MCU name
#MCU = atmega32u4
MCU = STM32F103 
​
# Bootloader selection
#BOOTLOADER = caterina
BOOTLOADER = stm32duino

The programmer I used was "ST-LINK V3 Mini", and the programming mode was SWD - vcc+io+clk+gnd.
after I ran "qmk fkash", it started OK then prompted:

> Compiling: quantum/matrix.c                                                                        In file included from ./lib/chibios/os/hal/include/hal_pal.h:174,
                 from ./lib/chibios/os/hal/include/hal.h:139,
                 from tmk_core/common/chibios/platform_deps.h:18,
                 from quantum/quantum.h:18,
                 from quantum/matrix.c:23:
tmk_core/common/chibios/pin_defs.h:226:25: error: 'GPIOF' undeclared here (not in a function); did you mean 'GPIOB'?
  226 | #    define F4 PAL_LINE(GPIOF, 4)
      |                         ^~~~~
./lib/chibios/os/hal/ports/STM32/LLD/GPIOv1/hal_pal_lld.h:81:26: note: in definition of macro 'PAL_LINE'
   81 |   ((ioline_t)((uint32_t)(port)) | ((uint32_t)(pad)))
      |                          ^~~~
./keyboards/crkbd/config.h:39:7: note: in expansion of macro 'F4'
   39 |     { F4, F5, F6, F7, B1, B3 }
      |       ^~
quantum/matrix.c:56:56: note: in expansion of macro 'MATRIX_COL_PINS'
   56 | static SPLIT_MUTABLE_COL pin_t col_pins[MATRIX_COLS] = MATRIX_COL_PINS;
      |                                                        ^~~~~~~~~~~~~~~
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [tmk_core/rules.mk:443: .build/obj_crkbd_rev1_default/quantum/matrix.o] Error 1

**Comment by rogerclarkmelbourne** [comment]
The file path 

tmk_core/common/chibios/pin_defs.h 

is not part of this bootloader code.

The bootloader does not contain or use a realtime OS, i.e. chibios
