### ISSUE TITLE
Which is the STM32F407VET6 Bootloader?

### ISSUE THREAD

**Issue by TrulyMarcus** [rogerclarkmelbourne/STM32duino-bootloader#119]
Short story is I'm trying to use the guide from https://www.electronicshub.org/how-to-upload-stm32f103c8t6-usb-bootloader/ to upload a Bootloader to a 3d printer board that uses the STM32F407VET6. However I can't find any User LED in its hardware documentation [https://github.com/makerbase-mks/MKS-Monster8/blob/main/hardware/MKS%20Monster8%20V1.0_002/MKS%20Monster8%20V1.0_002%20SCH.pdf](url) . 

Longer story is the board used to be recognized by my Mac, but I put a microsd card with a simple serial.print .bin file in it to see if I could upload code that way. It converted the file to .cur so I know it interpreted it somehow but the Arduino IDE and stm32 programmer won't show the board as connected on the USB port anymore. I hope using a FTDI or st link progammer to upload a Bootloader will fix this.

**Comment by rogerclarkmelbourne** [comment]
STM32F4 series devices are completely different to STM32F1 series.

This bootloader only works with STM32F1 devices
