### ISSUE TITLE
can this bootloader use in STM32F103RCT6?

### ISSUE THREAD

**Issue by mcykin** [rogerclarkmelbourne/STM32duino-bootloader#120]
i have a develope board which use STM32F103RCT6,can i download this bootloader?

**Comment by rogerclarkmelbourne** [comment]
Bootloader will work with the F103RCT but every board uses different GPIO pins for the button used to enter the bootloader.

Look in https://github.com/rogerclarkmelbourne/STM32duino-bootloader/tree/master/bootloader_only_binaries  for a binary which has the same pin as your board uses for its bootloader button.

If you don't find a precompiled binary that matches your board you'll need to modify and compile the code to suit your board

**Comment by mcykin** [comment]
hi,i've check my developed board,but i find out it didn't have any button except NRST pin.

![qq_pic_merged_1669527358850](https://user-images.githubusercontent.com/28498352/204120922-f575443e-d83e-400b-b198-0ee63823f628.jpg)

as you can see,this board only leave a RST switch and BOOT0/1 select pin.

so,which version of boodloader should i use? can i still use binaries/generic_boot20_pc13.bin to download?

**Comment by rogerclarkmelbourne** [comment]
Try asking on https://www.stm32duino.com

**Comment by Fusseldieb** [comment]
> so,which version of boodloader should i use? can i still use binaries/generic_boot20_pc13.bin to download?

I have the same board. Did you manage to get it working? What did it need?

**Comment by DFWJunior** [comment]
> > so,which version of boodloader should i use? can i still use binaries/generic_boot20_pc13.bin to download?
> 
> I have the same board. Did you manage to get it working? What did it need?

i think i find the way to use it.
so you need a usb-ttl device,it can find in many ways.

first,put BOOT0 switch to 1(3.3v), BOOT1 should be fine in default.
and you need to connect your TTL downloader to RCT6 int these ways:

3.3V -- 3.3V(Careful your TTL Voltage!)
TX -- A10
RX -- A9
GND -- GND

then it should be fine to download it,like,i'm using STM32's Demonstration GUI to downloade stm32duino bootloader to use QMK function.
