### ISSUE TITLE
WIndows 10 can't find a device

### ISSUE THREAD

**Issue by tanklist** [rogerclarkmelbourne/STM32duino-bootloader#121]
I use STM32F103 board (blue pill) with STM32duino-bootloader. I put the device into bootloader mode, and it appears in Windows Device Manager
![изображение](https://user-images.githubusercontent.com/40356992/216917948-401f2385-e732-41d2-89ac-79a0cadbbd35.png)
I checked ID of the device and it's correct:
![изображение](https://user-images.githubusercontent.com/40356992/216918067-4afc97b5-d764-4aec-9bc2-d8507ebd1fa7.png)
Then I select the upload method in Arduino IDE:
![изображение](https://user-images.githubusercontent.com/40356992/216918287-41b4f8a1-916b-44f3-b9c5-23722e10e461.png)
And after I started upload I got an error:
![изображение](https://user-images.githubusercontent.com/40356992/216918439-3becb2d8-eaa3-4265-97ba-4fd735f940e0.png)
It seems the loader can't find my device. But what the reason? It works correctly in Windows 7.

**Comment by rogerclarkmelbourne** [comment]
Try posting to https://www.stm32duino.com
