### ISSUE TITLE
Program uploaded with bootloader only starts after serial terminal connection

### ISSUE THREAD

**Issue by gebad** [rogerclarkmelbourne/STM32duino-bootloader#123]
Hardware:
board bluepill stm32f103cb (gd32f10x, ARM Cortex M3)
NRST button on R active low
Boot0 button active high
Key user-button available at PA0 active high
PA12 have a pull-up resistor 
Blue Led PB2

Development environment:
Platformio

My customisation:
Config.h
// added
#elif defined TARGET_GD32F1_GENERIC_F103_PB2
    #define LED_BANK GPIOB
    #define LED_PIN 2
    #define LED_ON_STATE 0
    #define FASTBOOT 1 
#else
Makefile and platform.ini adjusted accordingly.

Problem:
Program uploaded via bootloader only starts with serial terminal connection.
With reset or poweron-reset only bootloader is started. Without fastboot, the blue LED flashes according to the bootloader programme (very fast, fast and off).
What adjustments would I have to make so that the uploaded programme starts without a terminal connection via poweron reset?

With the bootloader
https://github.com/WeActTC/BluePill-Plus/blob/master/SDK/STM32F103C8T6/Arduino/Bootloader/STM32duino-bootloader-PB2.bin
poweron-reset does not work either.

Translated with www.DeepL.com

**Comment by rogerclarkmelbourne** [comment]
Issues are not a support forum.

Try  https://www.stm32duino.com
