### ISSUE TITLE
Failing to use the Bootloader on a custom Board with same Microprocessor

### ISSUE THREAD

**Issue by Y-e-Quit** [rogerclarkmelbourne/STM32duino-bootloader#124]
I created my own board with an STM32F103C8T6 and want to Programm it using USB, therefor I need your Bootloader. 

I have an LED on PC13 Pin connected, but use an Oscillator of 16MHz. I got told, when I want to use your Bootloader, I have to make changes specifically for my Board. 

**Which file do I have to change according to my needs?**

**Comment by rogerclarkmelbourne** [comment]
This is not an issue with the code for the boards which it supports
