### ISSUE TITLE
Changing the Pin PC14 to another Pin

### ISSUE THREAD

**Issue by Y-e-Quit** [rogerclarkmelbourne/STM32duino-bootloader#125]
# Problem # 
I have created my own board with the **STM32F103C8T6** Microprocessor on it. But thought I wouldnt need to add these two pin casue through space on the board itself. 

## Questions how to solve: ## 
- Changing the Pin from Pc14 to another Pin (_best would be in a range from Pa4 to Pa7 or PB1 and PB3 to PB7_) 
    **--> is this point nessesary?** 
- Changing the Oscillator Frequenzcy to HSE 16MHz (only have a 16MHz HSE on board)
- How to save the changes, to then **upload** the changes for a working board onto the STM32F103

**Comment by rogerclarkmelbourne** [comment]
duplicate issue
