### ISSUE TITLE
Not open serial after conect

### ISSUE THREAD

**Issue by nikitadan4pi** [rogerclarkmelbourne/STM32duino-bootloader#129]
I flashed "generic_pc13" bootloader version. After I plug usb into my PC I see one LibUSB device - MapleDFU. I see nothing COM ports, and cant download my sketch, what I need do?
I use BluePill with F103C6T6a MCU.

**Comment by davemaster** [comment]
Greetings,

[Here, in this link](https://www.electronicshub.org/getting-started-with-stm32f103c8t6-blue-pill/), a complete guide, FIRST OF ALL, view, and be careful with the pinouts for voltage (GND AND +5V), then, use an USB TO UART to program, without forget, put the BOT0 jumper (YELLOW JUMPER) in position HIGH. All is [there](https://www.electronicshub.org/getting-started-with-stm32f103c8t6-blue-pill/)


![STM32-BOOT-Selection](https://github.com/rogerclarkmelbourne/STM32duino-bootloader/assets/1075807/23b9afef-0aee-48f5-b27d-8bf2e0bbe159)
