### ISSUE TITLE
blupill and linux

### ISSUE THREAD

**Issue by MauroMombelli** [rogerclarkmelbourne/STM32duino-bootloader#13]
HI!

I have a strange issue, i'm using generic_boot20_pc13.bin downloaded the nov 13 13:04 on a bluepill.
AFTER uploading the first sketch, the AsciiTable example, every time i connect the USB dfu-util show 3 DFU but all UNKNOW and the upload will not work.

I then start to manually reset until eventually i get a good timing (dfu-util start about when the led start to blink slow before stopping) and from there i get the /dev/ttyACM0 and everything work flawlessy.

lsusb alway show only 1eaf:0003, while some friend tell me they also see a 1eaf:0004

**Comment by rogerclarkmelbourne** [comment]
Try going back a few revisions and see if the older binaries work

Are you running Linux ? 

The biggest change recently was to change to use a newer version of GCC, and we thought the only issue was that it failed to jump to the sketch

But there may be some other changes which didn't effect Windows

The most recent changes have been to reduce the time taken after the USB reset is received before the sketch runs. However your issue doesnt sound like its related to that change.

You could try making the bootloader using GCC ARM that the Arduino IDE uses i.e  4.8.x

 e..g 

```
make clean 
make generic-pc13
```

and see if that resolves the issue (in which case its a compiler issue ;-(

**Comment by MauroMombelli** [comment]
sorry updated comment above, the tty appear AFTER the first successfull upload, not the other way around. A friend of mine has used same version on windows and seems to work fine, another tested win + xubuntu and wors fine (30 ago 2016), he gave me the binary, tomorrow i'll try to find some time for the test

**Comment by MauroMombelli** [comment]
Btw on my macchine i also nave arm-none-eabi-gcc 6.2.0, what is the compiler version you had used? Which one is the one uses in the past?

**Comment by rogerclarkmelbourne** [comment]
I'm a bit confused.

Do you mean that TTY does not appear until after sketch upload? but that Upload is OK.

The bootloader does not contain any TTY code, it us only a bootloader and hence only enumerates as a DFU device

The TTY code is provided by the Arduino "sketch" (not the bootloader), because its is also possible to upload the Arduino sketch using STLink or JLink, and still have TTY (USB CDCACM)

**Comment by MauroMombelli** [comment]
Yes, the  first time after uploading dfu over serial, I see the dfu and
upload is fine. Then I upload a sketch (asciitable), even multiple time,
without issue. Then i disconnect the USB, reconnect, and I got the 3
"UNKNOW" DFU (instead of saying maple bootloader V1.0 blabla) and I have to
manually reset +upload until I got it working. After that, upload works as
long as I don't disconnect the USB (which is funny as I can see the USB get
enumerated every upload...)

**Comment by rogerclarkmelbourne** [comment]
Does the same problem occur if you run a simple "blink" sketch ?

(Or blink + count )

**Comment by MauroMombelli** [comment]
Yes

**Comment by MauroMombelli** [comment]
finally got some time, tested the version from 30 ago 2016 but is even worse, after uploading a sketch using the serial i don't t get the enumeration, and the blink does NOT blink despite the upload and reset getting reposrted as successfull!

**Comment by rogerclarkmelbourne** [comment]
This may be a hardware / OS issue

Probably best to register and post on www.stm32duino.com where more people can help you.

Very few people Watch this repo

**Comment by rogerclarkmelbourne** [comment]
Closed as this issue should be taken up on the forum
