### ISSUE TITLE
Use updater_stm32f1.ino for STM32F103CB

### ISSUE THREAD

**Issue by gonzzzales** [rogerclarkmelbourne/STM32duino-bootloader#130]
Hi!
I am trying to write bootloader with my scetch for STM32F103CB using updater_stm32f1.ino.
I take bootloader generic_boot20_pc13.bin and combine it with my scetch blink.ino.bin with tool mergesketch.exe.

Then in updater_stm32f1.ino i change const char maple_mini_boot20[] with my combined scetch.
Unfortunetly it not work. Allways stm32 freeze on "Writing flash page 8 of 15".

Please help me to understand, what is wrong?

**Comment by gonzzzales** [comment]
Is anybody here?

**Comment by rogerclarkmelbourne** [comment]
This is not a bug / issue with this source code.  Try posting to stm32duino.com
