### ISSUE TITLE
To to get a simple STM32CubeIDE application to work with this?

### ISSUE THREAD

**Issue by etale-cohomology** [rogerclarkmelbourne/STM32duino-bootloader#133]
I'm using an STM32F103C8 Bluepill with this bootloader and I can install, say, [QMK keyboard firmware](https://github.com/qmk/qmk_firmware) over USB and it works: first I flash the bootloader and then I install the QMK firmware over USB (using `dfu-util`); then, when I connect the Bluepill over USB and run `lsusb` (on a loop), for a couple of seconds I can see `Leaflabs Maple DFU interface` as a USB device, and then the QMK firmware takes over.

However, when I try to install a simple STM32CubeIDE USB HID application over USB, I can install it but it never runs: `lsusb` shows `Leaflabs Maple DFU interface` always and my firmware never takes over.
(However, the same application does work/run when I flash it directly to the STM32.)

How can I get it to work? Maybe I need to modify the linker script somehow to put things in places that this bootloader expects?

**Comment by rogerclarkmelbourne** [comment]
This issue is nothing to do with this source code.
