### ISSUE TITLE
Add shell script for adding the arm-none-eabi toolchain folder to the search path

### ISSUE THREAD

**Issue by gknauf** [rogerclarkmelbourne/STM32duino-bootloader#16]
Finf attached a shell script for adding the arm-none-eabi toolchain folder to the search path.
Tested on Linux and MinGW/MSYS.
Execute with: . set_toolchain_path.sh
The script should be added to the top level folder and the ".txt" extension removed.

Edit: re-uploaded script because I changed the var MSYSCON (to check if we are on Windows) to MSYSTEM since I just found that MSYS2 does no longer have it.

[set_toolchain_path.sh.txt](https://github.com/rogerclarkmelbourne/STM32duino-bootloader/files/718081/set_toolchain_path.sh.txt)

**Comment by rogerclarkmelbourne** [comment]
I don't think this is necessary

Anyone skilled enough to have the arm dev env installed will know how to do this themselves and not want to run a script to do this for them.
