### ISSUE TITLE
Maple RET6

### ISSUE THREAD

**Issue by skyng22003** [rogerclarkmelbourne/STM32duino-bootloader#18]
Hi Roger, for the Maple RET6 bootloader can I just take the Maple R5 and change the Flash and RAM sizes and compile it?

Thanks,
Sky

**Comment by rogerclarkmelbourne** [comment]
There's not really any difference in the memory settings between the different Make targets, the only difference is whether the board has the Maple / Maple-mini USB reset hardware or not and which pin the LED is on and which pin the "button" is on (if the board has a "button"

I'd just try the existing Maple RET6 binary, it will probably work for the R5

**Comment by rogerclarkmelbourne** [comment]
Closed due to inactivity
