### ISSUE TITLE
Combine STM32F1 and GD32F1

### ISSUE THREAD

**Issue by GrantM11235** [rogerclarkmelbourne/STM32duino-bootloader#26]
Because the STM32F1 and GD32F1 folders are so similar, I think it makes sense to combine them. I have made a branch for each in the hopes of eventually merging them together. I have gotten the diff down to three files: Makefile, config.h, and hardware.c. Makefile and config.h should be pretty strait forward to merge, but hardware.c looks like it could get messy.

Edit: For posterity, here are the last commits before the merge
STM32F1: d3c716a07eee9275c9291cca25aed948435ff980
GD32F1: 1818e3668123ff6914cffd86131cca59185599a7

**Comment by rogerclarkmelbourne** [comment]
I agree

There is very little difference in terms of the bootloader.

From what I can remember, only the PLL multipler would need to be changed, as the GD32 boards I have use a 12Mhz crystal instead of the normal 8Mhz one.

**Comment by GrantM11235** [comment]
I copied setupCLK() in hardware.c from STM32F1 to GD32F1, can you check that [this commit](https://github.com/GrantM11235/STM32duino-bootloader/commit/907db1b4bc1f05471e56442ebee124747e9ef758) looks right? It looks like PLL for the GD32F1 branch was set to 108MHz, is there any conflict if it is set to 72MHz like in the STM32F1 branch? It should be functionally equivalent otherwise.

**Comment by rogerclarkmelbourne** [comment]
72Mhz for both is fine.

I don't think 108Mhz works, as there isnt a matching USB PLL divider to make 48 Mhz

AFIK the only clock speeds that support USB are 48Mhz, 72Mhz, 96Mhz and 120Mhz

**Comment by GrantM11235** [comment]
Actually, it wasn't at 108MHz before, it was at 96MHz, the comment I was reading was outdated. I guess that doesn't really matter now that it is replaced though.

**Comment by rogerclarkmelbourne** [comment]
This is been done
