### ISSUE TITLE
Suggestion: Remove support for button and LED

### ISSUE THREAD

**Issue by GrantM11235** [rogerclarkmelbourne/STM32duino-bootloader#29]
Pros:
- Reduce number of build targets
- Support most/all current and future boards
- Eliminate confusion/danger for users with things attached to button/LED pins

Cons:
- Obviously no more button/LED support, but their usage appears to be undocumented, and is apparently unnecessary

Let me know if I missed anything, and tell me what you think.

**Comment by rogerclarkmelbourne** [comment]
People would not be happy if I removed the LED or button

Its written about and shown in many videos.

We could add a new build target which didnt have either, which people could use as a fallback

But unless someone has something connected to PC13 etc, they  can just use that version if a version with the LED pin for their board has not been built.

There is probably another way of reducing the number of makefile build targets by using makefile variables. 
The BlackMagic Probe firmware uses this method e.g. make PROBE_HOST=stlink

It uses the PROBE_HOST variable as the folder name for the compilation

I presume we could have something like 

make LED_PORT=PORT_C LED_PIN=13 BUTTON_PORT=PORT_B BUTTON_PIN=1 OUTFILE=generic_pc13

But as things are working as they stand, I do not have the time to completely change the build process and achieve exactly the same result as we currently have
