### ISSUE TITLE
Is there a matching bootloader for this maple mini or a new one required?

### ISSUE THREAD

**Issue by knopserl** [rogerclarkmelbourne/STM32duino-bootloader#35]
thanks a lot roger for your great work!

I have flashed the generic bootloader 12 (pb12) with an FTDI adapter and it works perfekt.
Now I have a set of STM32 maple mini ith 128k and two buttons. The board is labeled with d1= 33 and but=32. Now I'm uncertain which bootloader I should take?
Is it  	maple_mini_boot20.bin? I have tested the blink sketch and the led is on PB1. Does that match with the maple_mini_boot20 loader? Is there  a matching one for my boards with PB1 (d1=33?) and but=32?
Or can you build another binary for that board?
Here is the link to the product:
https://www.aliexpress.com/item/STM32F103RCBT6-ARM-Cortex-M3-leaflabs-Leaf-maple-mini-module-for-arduino-STM32/1878982440.html?spm=a2g0s.9042311.0.0.PI9eaS

greetings from Austria
Heinz

**Comment by rogerclarkmelbourne** [comment]
Hi Heinz

That board looks like a Maple mini, but perhaps its a clone with some things changed

Its not practical to produce bootloader for all possible stm32 boards, as there are around 20 possible pins for the LED, 19 for the button and 18 for the USB DISC pin i.e. Then allowing for button , LED and DISC pin  High or Low to activate, gives me 54720 possible bootloader targets

Anyone who has a non main-stream board, would need to compile their own bootloader
