### ISSUE TITLE
Compiling bootloader from scratch

### ISSUE THREAD

**Issue by TamojitSaha** [rogerclarkmelbourne/STM32duino-bootloader#43]
Hello @rogerclarkmelbourne,
After going through the instructions in [README](https://github.com/rogerclarkmelbourne/STM32duino-bootloader/blob/master/README.md), I tried run `make generic-pc13` from command line in Windows. But after going through the clean process, it stops and says "_The application was unable to start correctly(0xc0000142)_". I am using **WinAVR** _make_ command to compile. After closing the dialog box no new file was created in the _builds_ folder. I have attached a screenshot of my PC for your reference. Please help me find out what can possibly happen.

Here is the screenshot:
![img_20180429_231303](https://user-images.githubusercontent.com/20009733/39409331-da4c4b60-4bd4-11e8-87c7-fcd10fcd1b52.jpg)

**Comment by SandeepanSengupta** [comment]
If you have solved it, please post the solution here

**Comment by rogerclarkmelbourne** [comment]
Use GNU make

**Comment by TamojitSaha** [comment]
I have written full instruction to compile bootloaders from scratch in Windows Platform.

Hope it will be useful for someone.

[Here](https://github.com/TamojitSaha/Compiling_Arduino_STM32_bootloaders) is the link.

@rogerclarkmelbourne Please verify.

**Comment by TamojitSaha** [comment]
@rogerclarkmelbourne 
I suggest you add the steps to compile after @SandeepanSengupta  verifies the procedure. He is facing the same error as mine.
