### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by Jerome-PS** [rogerclarkmelbourne/STM32duino-bootloader#47]
Hi,

I have been browsing through the code and have found a few lines I do not understand.
For example, there is the function `void systemReset(void)` why is that called right after a reset, where it seems to set some registers to the value they get by hardware during reset? Was this inserted to address a specific issue? If there is no specific reason for it I would suggest this call is removed, so clock initialization can take place in the reset vector and data initialization (copy from FLASH to RAM and bss initialization to 0) can already benefit from a 72MHz clock.
`void systemReset(void)` is also called just before hand-off to the user code, which is a good thing, but it does not reinitialize everything, for example GPIO power is turned on but not turned off - which should be done if there is no specific reason against it.

In `setupClk(void)`, the first instruction is commented as "enable HSE", which is wrong the code enables both HSE and HSI, but HSI should already be activated by the hardware reset, so this is at best confusing...

That's it for now, if anyone can comment on those points, i'm all ears.

My ultimate goal would be able to fit the bootloader into 6kB, which would be 10% of the 64kB devices.

Cheers,
J.

**Comment by rogerclarkmelbourne** [comment]
This looks like a feature request.

If you want a smaller bootloader, take a look at the STM32 HID bootloader . I have a fork of it in my account, but use the original not my fork, as the fork will invariably be out of date
