### ISSUE TITLE
Add an option to build the firmware with PlatformIO

### ISSUE THREAD

**Issue by me21** [rogerclarkmelbourne/STM32duino-bootloader#48]
Perhaps it's worth considering? I'd like to use the bootloader for my custom board with 12 MHz crystal, but there is currently no combination of correct LED placement (PB0) and 12 MHz crystal for me.
And I'm developing everything in PlatformIO IDE, so I'd rather not install Arduino IDE just to compile the bootloader.
I will try to do it myself and submit a PR.

**Comment by ilya89vet** [comment]
Доброго времени Александр
Я если честно не понял что нужно сделать, что бы можно было загружать код в плату с боотлодером из Platformio IDE?

**Comment by me21** [comment]
Если бутлоадер уже прошит, то в файле `platformio.ini` основного проекта нужно указать `upload_method = dfu`.

If the bootloader has already been uploaded to the board, you should add a line `upload_method = dfu` to your primary project's `platformio.ini` file.

**Comment by ilya89vet** [comment]
upload_protocol = dfu я делал
При попытке загрузить код, плата перезагружается и определяется как
неизвестное устройство и загружаемый код не работает, после переполнения
USB плата определяется как Maple DFU. После этого приходится заново
прошивать Bootloader.

сб, 16 февр. 2019 г., 1:16 Alexandr Zarubkin notifications@github.com:

**Comment by me21** [comment]
Maple DFU означает, что плата находится в режиме бутлоадера. Заново его прошивать не надо. Попробуйте на простейшем примере помигать лампочкой. Если не сработает - покажите код.

Maple DFU means that bootloader is up and running, you don't need to reflash it again. Try the simplest "LED blink" code. If it won't work please show me the code.

**Comment by ilya89vet** [comment]
> Но это поддерживается только ядром Arduino авторства rogerclarkmelbourne

А как это ядро установить в PlatformIO?

**Comment by me21** [comment]
Вопросы установки Arduino в Platformio - https://community.platformio.org, https://docs.platformio.org

Для использования бутлоадера надо поставить драйвер, см. https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Maple-drivers

Questions related to installing Arduino to Platformio - https://community.platformio.org, https://docs.platformio.org

You need to install driver before using bootloader - https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Maple-drivers

**Comment by rogerclarkmelbourne** [comment]
The original issue is a feature request.

Subsequent posts in Russian seem to be a support request. Please read the Readme or search online about how to use the bootloader.

Issues are not a way to ask for support. There is no support. This is a free open source project, its non-commercial, hence there is no support

**Comment by me21** [comment]
@rogerclarkmelbourne can you please review the linked PR concerning the initial feature request?
