### ISSUE TITLE
Default  button pin is not PC12, but PC14

### ISSUE THREAD

**Issue by KAlexK** [rogerclarkmelbourne/STM32duino-bootloader#5]
Default  button pin is not PC12, but PC14. (In README.md)

**Comment by rogerclarkmelbourne** [comment]
Thanks

I have corrected the readme.md

**Comment by GrantM11235** [comment]
I believe this should also be changed in the next paragraph (line 46)

**Comment by rogerclarkmelbourne** [comment]
Which file ?

**Comment by GrantM11235** [comment]
README.md
