### ISSUE TITLE
Verification Failed - STM32F103C8T6

### ISSUE THREAD

**Issue by mab5vot9us9a** [rogerclarkmelbourne/STM32duino-bootloader#53]
Using a STM32F103C8T6 (*STM32F103C8T6 ARM CCortex-M3 STM32 Minimum System Board - Blue* to be precise) and a CP2102 to flash the bootloader the verification always fails and I don't know how to pinpoint my error.

I am using `python2.7 flash/stm32loader.py -v -p /dev/tty.SLAB_USBtoUART -w bootloader_only_binaries/generic_boot20_pc13.bin`

I set the `BOOT0` jumper to `1`, reset the board and run the command mentioned above.
It writes, it reads and then (only because of `-v`) I see `verification failed` and a list of all the locations where the mismatches are.

My wiring is as follows:
**CP2102 -> STM32F103C8T6**
`VCC (3.3V)` ->  `3.3`
`GND` -> `G`
`RX` -> `A9`
`TX` -> `A10`

Output of `stm32loader.py`:
```
Bootloader version 22
Chip id `['0x4', '0x10']'
Write 256 bytes at 0x8000000
...
Read 256 bytes at 0x8000000
...
Verification FAILED
7160 vs 7160
0x4: 0xf1 vs 0x71
0x5: 0x0 vs 0x1
0x8: 0x39 vs 0xf1
0x9: 0x1 vs 0x3
...
0x1bf4: 0x0 vs 0x63
0x1bf5: 0xc vs 0x8a
```

Any help would be appreciated.

**Comment by KennethBrandon** [comment]
I seem to have the same issue. Did you ever figure it out?

**Comment by mab5vot9us9a** [comment]
I got it to work at some point, but I was not able to pinpoint it to one specific issue since I tried a lot of different things, including changing the CP2102 drivers on my system... 
Sorry I can't be of more help :/

**Comment by rogerclarkmelbourne** [comment]
This is not a bug in the bootloader
