### ISSUE TITLE
Port to OLIMEX-STM32

### ISSUE THREAD

**Issue by AlirezaSadri** [rogerclarkmelbourne/STM32duino-bootloader#55]
Hi, 

I know that there has been requests to support OLIMEX-STM32 where LEDs are on PA1 and PA5, BUT is on PC9 and the DISC is on PC12. It seems this is how new maple rev5 is too. I'm not sure if they are currently supported. So I tried it myself by defining a new board in the Config file and the Makefile to support this board.
(I installed Ubuntu18, then Arduino, then inside Arduino I added SAM boards, I added Arduino STM and using the proper json I added STM32duino for STM32F103, I installed the driver from folder linux-64).

After programming the board with the bootloader 2.0 (using an FTDI cable and stm32flasher), The dmesg says:
[  565.356374] usb 3-2: new full-speed USB device number 6 using xhci_hcd
[  565.505403] usb 3-2: New USB device found, idVendor=1eaf, idProduct=0003
[  565.505408] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  565.505411] usb 3-2: Product: Maple 003
[  565.505414] usb 3-2: Manufacturer: LeafLabs
[  565.505416] usb 3-2: SerialNumber: LLM 003

But there is no ttyACM or ttyUSB and the "Port" inside Arduino is grayed out. I have tried changing the 45-rules accroding to:
https://wiki.stm32duino.com/index.php?title=Installation_on_Linux

But still, the tty port does not appear. Can I ask if I lack a driver or something?

I could use a hint
Thanks a lot

**Comment by rogerclarkmelbourne** [comment]
This is a question not an issue.

All community support for the bootloader and the Arduino core are via www.stm32duino.com
