### ISSUE TITLE
STM32F1 not being recognized

### ISSUE THREAD

**Issue by korishan** [rogerclarkmelbourne/STM32duino-bootloader#60]
I hope someone here might be able to help me. I have tried using various bootloaders you guys provided. My problem is when I connect up to the usb I get unrecognized device
"Unknown USB Device (Device Descriptor Request Failed)"

I get this on all 5 of the boards I just got. They are the STM32F103C8T6, in the blue pill layout.

When I got the boards, they had some type of blink program installed as PC13 will blink. But even if I upload a sketch through the FTDI link, it seems to not work. I can reflash using the Demonstrator GUI.

I'm not even sure what the proper Google search is to find a solution. "stm32 unknown usb device maple" didn't turn up anything that actually worked.

TIA,
Kori

**Comment by rogerclarkmelbourne** [comment]
Apart from the possibility of all 5 boards being defective

a) Is the board you are using compatible e.g. is it a BluePill or Maple mini etc, e.g. it will only work on F103 boards with 8Mhz Crystals
b) Are you using a USB cable that works (many cables don't have data wires)
c) You need drivers for windows. (see the arduino_stm32 repo windows drivers folder
d) What file did you flash to your board

The list is endless

**Comment by korishan** [comment]
Thanks for the reply, roger.

a) It is specifically this board: https://www.ebay.com/itm/323591665224. It has an 8Mhz crystal on the board.
b) I'm using a known good cable. It works just fine with my other devices (phones, tablet, arduino). So I know it's not the cable.
c) I've installed the drivers from that repo, which are basically reassignments to other built in drivers. I don't know if the VID/PID that was used in the batch file are the correct ones, tho, and not sure how to check the correct ones on the stm32 boards if they aren't being detected properly. 
d) I flashed using both generic_boot20_pc13.bin and generic_boot20_pc13_fastboot.bin and neither one worked. Both I got from this repo. I even tried maple_mini_boot20.bin just to see if that'd make a difference, but not.


I know the list can seem endless, but at least a good point in the right direction helps a bunch :)

Kori

**Comment by rogerclarkmelbourne** [comment]
That board is OK, but it has a known design fault that make it incompatible with some machines

See the section called "Hardware installation"

http://wiki.stm32duino.com/index.php?title=Blue_Pill

But the design fault doesn't usually manifest in your error and it only generally is a problem on a Mac 

I'm afraid I cant think why else it doesnt work.

Thousands of people use the bootloader so it does work for most people 

Generally all other support is via the STM32Duino community www.stm32duino.com  you could try posting there, as hardly anyone watches this repo

**Comment by korishan** [comment]
Alright, thanks for the help   :)  I'll check out the STM32Duino forum.
