### ISSUE TITLE
Compile error when the extended filename contains a blank

### ISSUE THREAD

**Issue by gerardwr** [rogerclarkmelbourne/STM32duino-bootloader#61]
Newbie for STM32duino here, I'm using a Mac.

The pathname of my sketch files contains a blank, something like:
```
/Users/name/Documents/My Data/Arduino/sketchname.ino
```

This results in Arduino compile errors like
```
/Users/name/Documents/My Data/Arduino/hardware/Arduino_STM32-master/tools/macosx/maple_upload: line 34: /Users/name/Documents/My: No such file or directory
```

As a quick fix I adapted the maple_upload source:
- Line 34 : replaced `$(dir)` with `"${DIR}"`
- Lines 44,48,53 : replaced `${DFU_UTIL}` with `"${DFU_UTIL}"`

I'm sure there's a neater way to fix the issue, but the quick fix worked for me.

Would it be possible to correct maple_upload so that it is compliant with pathnames containing a blank?

**Comment by rogerclarkmelbourne** [comment]
This is not an issue with the bootloader, its an issue with the arduino_stm32 core

Please repost the issue in that repo

**Comment by gerardwr** [comment]
Thanks for reply-ing and pointing me in the right direction. 

Found the same issue on arduino_stm32 core and a more simple temp fix in platform.txt
https://github.com/stm32duino/Arduino_Core_STM32/issues/256

**Comment by fpistm** [comment]
> Create a new issue there for uploading:
> [stm32duino/Arduino_Core_STM32#448](https://github.com/stm32duino/Arduino_Core_STM32/issues/448)

I've answered you about this issue.

**Comment by gerardwr** [comment]
@fpistm 

Ok, I'm confused, but opened a new issue here. Thanks.
https://github.com/rogerclarkmelbourne/Arduino_STM32/issues/600
