### ISSUE TITLE
Useing keil to open project

### ISSUE THREAD

**Issue by ForeverGeeker** [rogerclarkmelbourne/STM32duino-bootloader#63]
I'm trying to open STM32duino-bootloader project by Keil, is it work?
If yes, the lib of stm32 show errors like
stm32_lib\cortexm3_marco.c(55-136): Invalid line start
stm32_lib\c_only_startup.s (52-54): Lable missing from line start
etc.
at about 155 error(s)
Did I make some mistakes?

**Comment by rogerclarkmelbourne** [comment]
See the readme. 

This bootloader is compiled using GCC ARM.

It uses a normal Makefile

It probably won't compile using Keil unless you port it to Keil
