### ISSUE TITLE
CKS32F103C Compatibility

### ISSUE THREAD

**Issue by TzOk83** [rogerclarkmelbourne/STM32duino-bootloader#72]
There are so called "bluepills" boards with CKS32F103C MCU, that work only with a naze32_boot20.bin variant, but they have LED at PC13, as most generic "bluepill" boards. Flashing any other bootloader results in USB device not recognized (R10 changed to 1.5k).

It is also mentioned here: https://youtu.be/VE8-DCMXzo8?t=1424
In case of the STM32F103U equipped "bluepill", the naze32_boot20.bin works same as good as the generic_boot20_pc13.bin.

**Comment by rogerclarkmelbourne** [comment]
Only STM32 or perfect clones are supported
