### ISSUE TITLE
naze32_boot20.bin what is it for?

### ISSUE THREAD

**Issue by TzOk83** [rogerclarkmelbourne/STM32duino-bootloader#73]
What board is it designed for, there is no mention about in on Wiki. How is it different from generic or maple?

**Comment by juergs** [comment]
naze32_boot20.bin_ seems to deliver same functionality to BluePill-Board as MapleMini with virtual COM-Port for Arduino serial uploads.

**Comment by rogerclarkmelbourne** [comment]
No its not. The LED pin is different

For info on Naze32 see https://www.google.com/search?q=naze32

**Comment by juergs** [comment]
Sorry, but works really fine for my BluePill-board with LED on PC13 blinking and behaving like a MapleMini-Board and letting Arduino upload sketches under MapleMini-board-conditions.
Only having in mind the 64/128K flash size of F103C8.
@25:07:
https://www.youtube.com/watch?v=VE8-DCMXzo8 
:-)
