### ISSUE TITLE
Using Serial UART1

### ISSUE THREAD

**Issue by tinwinaung** [rogerclarkmelbourne/STM32duino-bootloader#8]
Hi Roger,

I can use bootloader with china stm32f103rbt6 (https://world.taobao.com/item/38857645794.htm?fromSite=main)

I can upload scratch via USB port now.
But I also want to use existing Serial UART1 that I used to upload scratch before.

How can I use it in Ardunio code?
I try using Serial.print (and) USBSerial serial_debug;debug.print but all come out from maple_mini come port.

(I try to register http://www.stm32duino.com/index.php to ask this question but I did not receive activation email)

regards,
TIN

**Comment by tinwinaung** [comment]
Found out i need to use the following
Serial1.println("OK");

**Comment by rogerclarkmelbourne** [comment]
Hi @tinwinaung 

Yes.

When using the bootloader upload selection

Serial is USB Serial
Serial1 is the first hardware serial
Serial2 is the second hardware serial 
etc

If you are not using the bootloader (e.g. USB to Serial for upload) then Serial is hardware serial1

**Comment by rogerclarkmelbourne** [comment]
PS.

What is your username on the forum. I will manually activate for you..

**Comment by rogerclarkmelbourne** [comment]
I have manually activated you account

**Comment by tinwinaung** [comment]
Hi Roger,

Sorry for late reply. Yes, I can login now.
