### ISSUE TITLE
Bootloader sketch "updater_stm32f1" not compiling

### ISSUE THREAD

**Issue by dorinclisu** [rogerclarkmelbourne/STM32duino-bootloader#82]
- Arduino 1.8.10
- STM32 Cores 1.8.0

`updater_stm32f1.ino` does not compile and throws a lot of errors like type errors and Serial methods not being found.

As far as I can see this is the only way to update the Maple Mini bootloader, or is there any other?

**Comment by rogerclarkmelbourne** [comment]
STM32 Cores 1.8.0 ??

Which repo is this ?

**Comment by dorinclisu** [comment]
This is the repo
https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/master/STM32/package_stm_index.json

**Comment by rogerclarkmelbourne** [comment]
It’s that sketch is only compatible with my STM32 core, which predates the official core by several years
