### ISSUE TITLE
Problem after uploading bootloader to stm32 Blue Pill

### ISSUE THREAD

**Issue by klimma1508** [rogerclarkmelbourne/STM32duino-bootloader#84]
Hello, I Uploaded bootloader generic_boot_20_pc13.bin and now I can't upload anything to stm32 BluePill. I tried to upload a new bootloader using a serial converter and software flash loader demo and doesn't work. then I try to upload bootloader using ST-Link v2 and software stm32 link utility and same result. It doesn't work and USB cannot be recognized. Where I make a mistake?
Thank you
Martin

**Comment by mikegleasonjr** [comment]
@klimma1508 what did you do, I have trouble with bluepills too
