### ISSUE TITLE
STM32F1 not being recognized by windows with a 12MHz Crystal

### ISSUE THREAD

**Issue by ccccmagicboy** [rogerclarkmelbourne/STM32duino-bootloader#93]
I hope someone here might be able to help me out. My problem is when I connect up to the usb I get unrecognized device "Unknown USB Device (Device Descriptor Request Failed)". My board is a custom board with STM32F103RCT6 AND 12MHz crystal, and when burn the binaries from here, the board PC13 will blink a led, but without a successful usb 
![7E624D43-6422-47a3-A318-3D9701511BCA](https://user-images.githubusercontent.com/4132539/81299462-d8893e80-90a8-11ea-9e91-957c5a31ef7e.png)

**Comment by rogerclarkmelbourne** [comment]
You will need to make a new build target as most other boards have a 8MHz crystal

See config.h section for TARGET_GD32F1_GENERIC_F103_PC13 which has a 12Mhz crystal

**Comment by ccccmagicboy** [comment]
Great! Thanks!!!

**Comment by rogerclarkmelbourne** [comment]
No worries
